### PR TITLE
[RFC] Two recipes for regular flex and flex_installer in one repo: use python_requires

### PR DESCRIPTION
**Pull request by madebr**
In response to bincrafters/community#625

This pr is very similar to #4 in that it creates multiple recipes in one repo.
This main difference is that this one is using `python_requires`.
This allows the common logic to be put in a common base class `flex_base`, which is subclassed by `flex_installer` and `flex`.

Imho, it looks much cleaner.
But alas, it has a major problem (and showstopper):
- The `python_requires` in the flex and flex_installer recipe requires a full conan reference.
In this pr, this reference is hardcoded to `flex_base/2.6.4@bincrafters/stable` which is not correct.
The username and channel of flex_base should default to be the same as the username and channel of the flex_installer and flex recipe.

I do not know whether this is a limitation of `python_requires` or a limitation of my knowledge.
Imho, a ConanFile class should have the ability to override the username and channel of a python_requires.
Please comment if you know how to fix this.

Notes:
- depends on conan-io/conan-package-tools#325
- depends on conan-io/conan-package-tools#331
- I don't like the logic to export and upload `flex_base` in `build.py`

### CODE REVIEW

**Comment by jgsogo** [comment]
@madebr, about the `python_requires` _issue_ I can point you to this comment https://github.com/conan-io/conan/issues/4355#issuecomment-456310674, Conan needs to know which `python_requires` to use (`flex_base`) before trying to resolve the recipe (`flex`). The reason for this is that a `python-requires` might affect how the reference is computed and thus the pyreq should be fully resolved before, think about something like this:

```python

base = python_requires("name/version@user/channel")

class MyLib(ConanFile):
    name = "mylib"
    version = base.compute_my_version()
```

how could I know `MyLib::version` without locking the `base = python_req...`?

**Comment by madebr** [comment]
@jgsogo Thanks for the tip. Good to know that an explicit version is required in derived conan classes.

My main problem/question remains though: the dependency on `flex_base/2.6.4@bincrafters/stable` is explicit. This will make it impossible to create a flex package for the testing channel without changing the string to `flex_base/2.6.4@bincrafters/testing`.

In other words, this is impossible:
```
conan export flex_base someuser/somechannel
conan create flex_installer someuser/somechannel
conan create flex someuser/somechannel
```

**Comment by jgsogo** [comment]
It cannot depend on the version of the recipe that is using the python requires, but you can do this without any problem:

```python

username = os.getenv("CONAN_USERNAME")
channel = os.getenv("CONAN_CHANNEL")

base = python_requires("flex_base/2.6.4@{}/{}".format(username, channel))

class MyLib(base.ConanFile):
    name = "flex"
    ...

```

and those env variables can be populated from the command line or CI itself.

**Comment by madebr** [comment]
@jgsogo 
The problem with that approach is that those variables are not defined when this package is used as a dependency.

If a package has a `build_requires("flex_installer/2.6.4@bincrafters/stable")`, an error will be thrown because `flex_base/2.6.4@None/None` is not found.
Using a default in `get_env` is also not appropriate.

Apart from that, I don't think it is good design to let environment variables define dependencies.
The dependency graph should be independent of environment variables.

**Comment by jgsogo** [comment]
Now I understand your problem, this is more related to this other issue (https://github.com/conan-io/conan/issues/3988). I think we haven't come up with a solution yet 😞

**Comment by SSE4** [comment]
outdated by https://github.com/bincrafters/conan-flex/pull/7

**Pull request closed without merging**
