### PR TITLE
testing->stable

### PR DESCRIPTION
**Pull request by ericLemanissier**

### CODE REVIEW

**Comment by ericLemanissier** [comment]
help @Croydon .travis.yml have diverged, and I'm not sure how the conflict should be resolved !

**Comment by ericLemanissier** [comment]
LGTM

**Review by Croydon — APPROVED** [review]

**Comment by ericLemanissier** [comment]
Is it expected that the only merge option is "rebase and merge", and "create a merge" commit is "not enabled for this repository ?

**Comment by Croydon** [comment]
Yes, it is in the default settings, just not applied to every repo

**Pull request merged**
