### PR TITLE
Added flex tool binary in the final package

### PR DESCRIPTION
**Pull request by madduci**
The binary executable ´flex´ is required by other conan-packages (e.g. gSOAP, Thrift) during their build phase.

This change enables the delivery of the flex to systems where it is not available and it is more comparable to whatwinflexbison delivers for Windows.

### CODE REVIEW

**Comment by uilianries** [comment]
@madduci `flex_installer` is not enough for you case? 

we have two packages for Flex project, flex: only lib and headers, and flex_installer: only the executable

**Comment by madduci** [comment]
Hi @uilianries 

thanks for the reply. I didn't know about this package, with `flex_installer` it works. I can remove the pull request, but a question: isn't maintaining 2 projects with (almost) the same build process and changing the packaging a little too much to be managed?

**Comment by uilianries** [comment]
Yes, but at same time you only want to install flex binary, not the libraries, it sounds like build_requirements only. Also, projects like Protobuf, binary and libraries can consumed by different archs on same build. Sometimes it's annoying keeping two projects, but it's necessary.

We have more installers, as bison, cmake, ...

**Comment by uilianries** [comment]
closing this PR as flex_installer is enough.

**Pull request closed without merging**
